lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
app_name = 'lab_1'

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^lab-2-addon/', include('lab_2_addon.urls')),
    re_path(r'^story-1/', include('story_1.urls')),
    re_path(r'', include('story_3.urls')),
    re_path(r'schedule/', include('story_5.urls')),
    re_path(r'profile-accordion/', include('story_7.urls')),
    re_path(r'book/', include('story_8.urls')),
    re_path(r'user/', include('story_9.urls')),
]

handler404 = 'story_3.views.error404'

story_5/urls.py
from django.urls import path
from . import views

app_name = 'story_5'

urlpatterns = [
    path('', views.schedule, name='schedule'),
    path('edit/', views.edit_schedule, name='edit_schedule'),
    path('<int:sched_id>/', views.view_schedule, name='view_schedule'),
]

story_5/models.py
from django.db import models
from django.contrib.auth.models import User

LENGTH = 128

class Category(models.Model):
    name = models.CharField(max_length=LENGTH)
    color = models.CharField(max_length=7)

    def __str__(self):
        return self.name


class Schedule(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=LENGTH)
    start = models.DateTimeField()
    end = models.DateTimeField()
    place = models.CharField(max_length=LENGTH)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

story_5/forms.py
from django import forms
from .models import Category

LENGTH = 128

class ScheduleForm(forms.Form):
    schedule_name = forms.CharField(
        label='Nama Kegiatan',
        max_length=LENGTH,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    start = forms.DateTimeField(
        label='Waktu Mulai',
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#id_start',
            'placeholder': 'dd/mm/yyyy hh:mm',
        }),
    )
    end = forms.DateTimeField(
        label='Waktu Selesai',
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#id_end',
            'placeholder': 'dd/mm/yyyy hh:mm',
        }),
    )
    place = forms.CharField(
        label='Tempat',
        max_length=LENGTH,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        label='Kategori',
        required=False,
        widget=forms.widgets.Select(attrs={'class': 'form-control'}),
    )

    def clean_end(self):
        if self.cleaned_data['end'] < self.cleaned_data['start']:
            raise forms.ValidationError('Waktu Selesai tidak boleh kurang dari Waktu Mulai')

        return self.cleaned_data['end']

story_5/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from .forms import ScheduleForm
from .models import Schedule

DAYS = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jum\'at', 'Sabtu', 'Minggu']
MONTHS = ['', 'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli',
          'Agustus', 'September', 'Oktober', 'November', 'Desember']


def schedule(request):
    if request.method == 'POST':
        form = ScheduleForm(request.POST)

        if form.is_valid():
            sched = Schedule(
                user=User.objects.get(id=1),
                name=form.cleaned_data['schedule_name'],
                start=form.cleaned_data['start'],
                end=form.cleaned_data['end'],
                place=form.cleaned_data['place'],
                category=form.cleaned_data['category'],
            )
            sched.save()

            return redirect('story_5:schedule')

    else:
        form = ScheduleForm()

    context = {
        'form': form,
        'schedules': Schedule.objects.all().order_by('start'),
        'current_time': timezone.now(),
        'horizontal': ['start', 'end', 'category', 'color'],
    }

    return render(request, 'story_5/schedule.html', context)

def edit_schedule(request):
    if request.method == 'POST':
        if 'delete' in request.POST.keys():
            get_object_or_404(Schedule, id=request.POST['delete']).delete()

    return redirect('story_5:schedule')

def view_schedule(request, sched_id):
    sched = get_object_or_404(Schedule, id=sched_id)


    context = {
        'schedule': {
            'Nama Kegiatan': sched.name,
            'Waktu Mulai': sched.start.strftime("{}, %d {} %Y @ %H:%M").format(
                DAYS[sched.start.weekday()],
                MONTHS[sched.start.month],
            ),
            'Waktu Selesai': sched.end.strftime("{}, %d {} %Y @ %H:%M").format(
                DAYS[sched.end.weekday()],
                MONTHS[sched.end.month],
            ),
            'Tempat': sched.place,
            'Kategory': sched.category,
        }
    }

    return render(request, 'story_5/schedule_detail.html', context)

story_5/templates/story_5/schedule.html
{% extends 'base.html' %}

{% block style %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
<style>
#schedules .row {
  margin-top: 15px;
  margin-bottom: 15px;
  padding: 15px 0;
}
#schedules button[name=delete] {
  background: none;
  border: none;
  font-size: 1.1rem;
  padding: 0;
}
</style>
{% endblock %}

{% block content %}
<section>
  <div class="win-sm">
    <h1>Buat Jadwal</h1>
  </div>
  <div class="win-sm">
    <form action="{% url 'story_5:schedule' %}" method="POST">
      {% csrf_token %}
      {% for field in form %}

      {% if field.name not in horizontal %}
      <div class="form-group">
        <label for="id_{{ field.name }}">{{ field.label }}<span class="t-red">*</span></label>
        {{ field }}
        {% if field.errors %}
        <ul>
          {% for error in field.errors %}
          <li>{{ error }}</li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>

      {% elif field.name == 'start' %}
      <div class="row flex-column flex-md-row">
        <div class="form-group col">
          <label for="id_{{ form.start.name }}">{{ form.start.label }}<span class="t-red">*</span></label>
          <div class="input-group date" id="id_{{ form.start.name }}" data-target-input="nearest">
            {{ form.start }}
            <div class="input-group-append" data-target="#id_{{ form.start.name }}" data-toggle="datetimepicker">
              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
            </div>
          </div>
          {% if form.start.errors %}
          <ul>
            {% for error in form.start.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="form-group col">
          <label for="id_{{ form.end.name }}">{{ form.end.label }}<span class="t-red">*</span></label>
          <div class="input-group date" id="id_{{ form.end.name }}" data-target-input="nearest">
            {{ form.end }}
            <div class="input-group-append" data-target="#id_{{ form.end.name }}" data-toggle="datetimepicker">
              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
            </div>
          </div>
          {% if form.end.errors %}
          <ul>
            {% for error in form.end.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
      </div>

      {% elif field.name == 'category' %}
      <div class="row flex-column flex-md-row">
        <div class="form-group col">
          <label for="id_{{ form.category.name }}">{{ form.category.label }}</label>
          {{ form.category }}
          {% if form.category.errors %}
          <ul>
            {% for error in form.category.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
      </div>
      {% endif %}

      {% endfor %}
      <p>
      <i><span class="t-red">*</span>Wajib Diisi</i>
      <br>
      </p>
      <button class="button" type="submit" name="submit">Buat Jadwal</button>
    </form>
  </div>
</section>
<section id="schedules">
  <div class="win-sm">
    <h1>Jadwal</h1>
  </div>
  <div class="container-fluid">
    <form action="{% url 'story_5:edit_schedule' %}" method="POST">
      {% csrf_token %}
      {% for schedule in schedules %}
      <div class="row b-light{% if schedule.end < current_time %} t-grey{% endif %}" style="border: 2px solid {% if schedule.category %}{{ schedule.category.color }}{% else %}#EBF1F5{% endif %}">
        <div class="col-5 col-md-3">
          {{ schedule.start|date:"d/m/Y G:i" }}
        </div>
        <div class="d-none d-md-block col-3">
          {{ schedule.end|date:"d/m/Y H:i" }}
        </div>
        <div class="col-5">
          <a href="{% url 'story_5:view_schedule' schedule.id %}">
            {{ schedule.name }}
          </a>
        </div>
        <div class="col-1">
          <button type="submit" name="delete" value="{{ schedule.id }}">
            <i class="fa fa-trash"></i>
          </button>
        </div>
      </div>
      {% endfor %}
    </form>
  </div>
</section>
{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
<script>
  $(function () {
    $("#id_start").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
    $("#id_end").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });
</script>
{% endblock %}

story_5/templates/story_5/schedule_detail.html
{% extends 'base.html' %}

{% block style %}
<style>
#footer {
  position: absolute;
  bottom: 0;
  width: 100vw;
}
#detail .col-4 {
  font-weight: bold;
}
</style>
{% endblock %}

{% block content %}
<section id="detail">
  <div class="win-sm">
    <h1>Detil Jadwal</h1>
  </div>
  <div>
    <div class="container-fluid b-light">
      <div class="win-sm py-4">
        {% for key, value in schedule.items %}
        <div class="row">
          <div class="col-4">{{ key }}</div>
          <div class="col-auto t-blue">:</div>
          <div class="col-7">{{ value }}</div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
{% endblock %}