lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
app_name = 'lab_1'

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^lab-2-addon/', include('lab_2_addon.urls')),
    re_path(r'^story-1/', include('story_1.urls')),
    re_path(r'', include('story_3.urls')),
    re_path(r'schedule/', include('story_5.urls')),
    re_path(r'profile-accordion/', include('story_7.urls')),
    re_path(r'book/', include('story_8.urls')),
    re_path(r'user/', include('story_9.urls')),
]

handler404 = 'story_3.views.error404'

story_8/urls.py
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.search_book, name='book'),
    path('get', views.get_book_list, name='get_book'),
]

story_8/models.py
from django.db import models

# Create your models here.

story_8/views.py
from django.shortcuts import render
from django.http import JsonResponse, Http404
import requests

# Create your views here.
def search_book(request):
    return render(request, 'story_8/search_book.html')

def get_book_list(request):
    if request.is_ajax():
        response = requests.get(
            "https://www.googleapis.com/books/v1/volumes?q={}".format(
                request.GET["q"]
            ))
        return JsonResponse(response.json())
    raise Http404()

story_8/templates/story_8/search_book.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'story_8/css/search_book.css' %}">
{% endblock %}

{% block content %}
<section>
  <div class="win-sm">
    <h1>Cari Buku<span class="t-blue">:</span></h1>
  </div>
  <div class="win-sm d-sm-flex mb-4">
    <input type="text" name="q" class="form-control" placeholder="Searching searching di perut">
    <button class="button mt-3 mt-sm-0 ml-sm-3" id="search">Cari</button>
  </div>
  <div class="win-sm">
    <div id="book-header" class="d-none d-md-block font-weight-bold b-light">
      <div class="row mx-0">
        <div class="col-3 p-2">Gambar</div>
        <div class="col-3 p-2">Judul Buku</div>
        <div class="col-3 p-2">Penulis</div>
        <div class="col-3 p-2">Publisher</div>
      </div>
    </div>
    <div id="book-table">
    </div>
  </div>
</section>
{% endblock %}

{% block script %}
<script>
  var get_book_url = "{% url 'story_8:get_book' %}?q="
</script>
<script src="{% static 'story_8/js/get_book.js' %}"></script>
{% endblock %}