lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
app_name = 'lab_1'

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^lab-2-addon/', include('lab_2_addon.urls')),
    re_path(r'^story-1/', include('story_1.urls')),
    re_path(r'', include('story_3.urls')),
    re_path(r'schedule/', include('story_5.urls')),
    re_path(r'profile-accordion/', include('story_7.urls')),
    re_path(r'book/', include('story_8.urls')),
    re_path(r'user/', include('story_9.urls')),
]

handler404 = 'story_3.views.error404'

story_9/urls.py
from django.urls import path

from . import views

app_name = 'story_9'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
]

story_9/models.py
from django.db import models

# Create your models here.

story_9/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm,
                                       UsernameField)
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'username')
        field_classes = {'username': UsernameField}
        labels = {
            'first_name': 'Nama',
            'username': 'Username',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].error_messages = {
            'unique': 'Seorang pengguna dengan Username yang sama sudah ada.',
        }
        self.error_messages['password_mismatch'] = 'Konfirmasi sandi tidak sama.'
        self.fields['password1'].help_text = (
            'Panjang minimal 6 karakter. Tidak boleh seluruhnya angka.'
        )

    def clean_password1(self):
        password = self.data.get('password1')
        if len(password) < 6:
            raise forms.ValidationError('Password terlalu pendek.')
        if str(password).isdigit():
            raise forms.ValidationError('Password tidak boleh angka semua.')
        if password in 'qwertyuiopasdfghjklzxcvbnm'\
                or password == password[0:1] * len(password):
            raise forms.ValidationError('Password terlalu mudah ditebak.')
        return password

    # disable password verification
    def _post_clean(self):
        super(forms.ModelForm, self)._post_clean()


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].label = 'Username'
        self.error_messages['invalid_login'] = (
            "Masukkan Username dan sandi yang benar. "
            "Penulisan huruf besar/kecil berpengaruh."
        )

story_9/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.shortcuts import redirect, render

from .forms import RegisterForm, LoginForm


def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, 'Selamat Datang, Kak ' + user.first_name)
            return redirect('/')
    else:
        form = LoginForm()

    context = {
        'form': form,
    }

    return render(request, 'story_9/login.html', context)

def register_user(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Selamat Datang, Kak ' + user.first_name)
            return redirect('/')
    else:
        form = RegisterForm()

    context = {
        'form': form,
    }

    return render(request, 'story_9/register.html', context)

def logout_user(request):
    logout(request)
    messages.success(request, 'Anda berhasil keluar')
    return redirect('story_3:index')

story_9/templates/story_9/login.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
th, td {
  vertical-align: top;
  padding: 0.3rem 0;
}
th {
  padding-right: 0.5rem;
}
</style>
{% endblock %}

{% block content %}
<section>
  <div class="win-sm">
    <h1>Masuk<span class="t-blue">:</span></h1>
  </div>
  <div class="win-sm">
    <form method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <button type="submit" class="button my-3">Masuk</button>
    </form>
    Belum punya akun? <a href="{% url 'story_9:register' %}">Daftar</a>
  </div>
</section>
{% endblock %}

{% block script %}
{% endblock %}

story_9/templates/story_9/register.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
th, td {
  vertical-align: top;
  padding: 0.3rem 0;
}
th {
  padding-right: 0.5rem;
}
</style>
{% endblock %}

{% block content %}
<section>
  <div class="win-sm">
    <h1>Daftar<span class="t-blue">:</span></h1>
  </div>
  <div class="win-sm">
    <form action="{% url 'story_9:register' %}" method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <button type="submit" class="button">Daftar</button>
    </form>
  </div>
</section>
{% endblock %}

{% block script %}
{% endblock %}