lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
app_name = 'lab_1'

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^lab-2-addon/', include('lab_2_addon.urls')),
    re_path(r'^story-1/', include('story_1.urls')),
    re_path(r'', include('story_3.urls')),
    re_path(r'schedule/', include('story_5.urls')),
    re_path(r'profile-accordion/', include('story_7.urls')),
    re_path(r'book/', include('story_8.urls')),
    re_path(r'user/', include('story_9.urls')),
]

handler404 = 'story_3.views.error404'

story_1/urls.py
from django.urls import path

from . import views

app_name = 'story_1'

urlpatterns = [
    path('', views.index, name='index'),
]

story_3/urls.py
from django.urls import path

from . import views

app_name = 'story_3'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('404/', views.error404),
]

story_5/urls.py
from django.urls import path
from . import views

app_name = 'story_5'

urlpatterns = [
    path('', views.schedule, name='schedule'),
    path('edit/', views.edit_schedule, name='edit_schedule'),
    path('<int:sched_id>/', views.view_schedule, name='view_schedule'),
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.accordion, name='accordion'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="preload b-primary">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Okto | Pengembang Web{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
<style>
.button {
  background: url("{% static 'images/arrow.svg' %}") right 1rem center no-repeat;
}
</style>
{% block style %}{% endblock %}
  </head>
  <body class="t-primary b-primary">
    <div id="container">
      <!-- Navbar -->
      <nav class="navbar navbar-default fixed-top navbar-expand-lg navbar-light t-grey b-primary">
        <a class="navbar-brand" href="{% url 'story_3:index' %}">Okto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% with url_name=request.resolver_match.url_name %}
            <li class="nav-item">
              <a class="nav-link{% if url_name == 'index' %} active{% endif %}" href="{% url 'story_3:index' %}">Beranda</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if url_name == 'profile' %} active{% endif %}" href="{% url 'story_3:profile' %}">Profil</a>
            </li>
            {% comment %}
            <li class="nav-item">
              <a class="nav-link{% if url_name == 'accordion' %} active{% endif %}" href="{% url 'story_7:accordion' %}">Accordion</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if url_name == 'schedule' %} active{% endif %}" href="{% url 'story_5:schedule' %}">Jadwal</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if url_name == 'book' %} active{% endif %}" href="{% url 'story_8:book' %}">Buku</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Lain-lain
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'story_1:index' %}">Story 1</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'lab_1:index' %}">Lab 1</a>
              </div>
            </li>
            {% endcomment %}
            {% endwith %}
            <li id="nav-contacts" class="nav-item d-sm-none">
              <a href="mailto:git.lepiku@gmail.com" target="_blank" rel="noopener noreferrer">
                <i class="fa fa-envelope-o"></i>
              </a>
              <a href="https://www.linkedin.com/in/muhammad-oktoluqman-fakhrianto-3951a7180/" target="_blank" rel="noopener noreferrer">
                <i class="fa fa-linkedin-square"></i>
              </a>
              <a href="https://gitlab.com/lepiku" target="_blank" rel="noopener noreferrer">
                <i class="fa fa-gitlab"></i>
              </a>
              <a href="https://github.com/lepiku" target="_blank" rel="noopener noreferrer">
                <i class="fa fa-github"></i>
              </a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item my-auto">
              <label class="switch">
                <input type="checkbox" id="change-theme">
                <span class="slider round"></span>
              </label>
            </li>
            {% comment %}
            <li class="nav-item">
              {% if request.user.is_authenticated %}
              <a class="nav-link" href="{% url 'story_9:logout' %}">({{ request.user.first_name }}) <span class="t-blue">Keluar</span></a>
              {% else %}
              <a class="nav-link" href="{% url 'story_9:login' %}"><span class="t-blue">Masuk</span></a>
              {% endif %}
            </li>
            {% endcomment %}
          </ul>
        </div>
      </nav>
      <!-- Floating Contacts -->
      <div id="floating-contact" class="d-none d-sm-flex">
        <p>
        <a href="mailto:git.lepiku@gmail.com" target="_blank" rel="noopener noreferrer">
          <i class="fa fa-envelope-o"></i>
        </a>
        <br>
        <a href="https://www.linkedin.com/in/muhammad-oktoluqman-fakhrianto-3951a7180/" target="_blank" rel="noopener noreferrer">
          <i class="fa fa-linkedin-square"></i>
        </a>
        <br>
        <a href="https://gitlab.com/lepiku" target="_blank" rel="noopener noreferrer">
          <i class="fa fa-gitlab"></i>
        </a>
        <br>
        <a href="https://github.com/lepiku" target="_blank" rel="noopener noreferrer">
          <i class="fa fa-github"></i>
        </a>
        </p>
      </div>
      <!-- Content -->
      {% block content %}{% endblock %}
      {% if messages %}
      <div class="messages">
        <ul>
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}
      <!-- Footer -->
      <section id="footer" class="t-secondary b-secondary">
        <div class="win-sm">
          <h2>Kontak<span class="t-blue">:</span></h2>
          <p>
          <a href="mailto:git.lepiku@gmail.com" target="_blank" rel="noopener noreferrer">
            <i class="fa fa-envelope-o"></i>
          </a>
          <a href="https://www.linkedin.com/in/muhammad-oktoluqman-fakhrianto-3951a7180/" target="_blank" rel="noopener noreferrer">
            <i class="fa fa-linkedin-square"></i>
          </a>
          <a href="https://gitlab.com/lepiku" target="_blank" rel="noopener noreferrer">
            <i class="fa fa-gitlab"></i>
          </a>
          <a href="https://github.com/lepiku" target="_blank" rel="noopener noreferrer">
            <i class="fa fa-github"></i>
          </a>
          </p>
        </div>
      </section>
      <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="{% static 'story_7/js/change_theme.js' %}"></script>
      <script>
        setTimeout(function() {
          $('.messages').fadeOut('fast');
        }, 2000);
      </script>
      {% block script %}{% endblock %}
    </div>
  </body>
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}